export const panels = [
    {
        id: 1,
        className: 'icon-text',
        type: 'text',
        text: 'text',
        active: 1,
    },
    {
        id: 2,
        className: 'icon-image',
        type: 'image',
        text: 'image',
        active: 1,
    },
    {
        id: 3,
        className: 'icon-film',
        type: 'gif',
        text: 'gif',
        active: 1,
    },
    {
        id: 4,
        className: 'icon-button',
        type: 'button',
        text: 'button',
        active: 1,
    },
    {
        id: 5,
        className: 'icon-divider',
        type: 'divider',
        text: 'divider',
        active: 1,
    },
    {
        id: 6,
        className: 'icon-spacer',
        type: 'spacer',
        text: 'spacer',
        active: 1,
    },
    {
        id: 7,
        className: 'icon-code',
        type: 'code',
        text: 'code',
        active: 1,
    },
    {
        id: 8,
        className: 'icon-share-alt',
        type: 'social',
        text: 'social',
        active: 1,
    },
    {
        id: 9,
        className: 'icon-video-camera',
        type: 'video',
        text: 'video',
        active: 1,
    },
    {
        id: 10,
        className: 'icon-cube',
        type: 'cube',
        text: 'product',
        active: 0,
    },
    {
        id: 11,
        className: 'icon-hourglass-1',
        type: 'countdown',
        text: 'countdown',
        active: 0,
    },
];
